kernel: patch: patch kernel before supersu
Patching the kernel after the supersu can cause issue. Supersu perform a backup of the kernel ramsdik before the kernel patch and save it in the data partition.
Flashing supersu over the installation will restore the unpatched kernel and will cause issue.
Now the kernel is patched before the supersu installation, and will remove the dm-verity and forceencryption.
Else supersu will do that as it shoudl.

diff --git a/device/OnePlus3-ce/aroma/updater-script b/device/OnePlus3-ce/aroma/updater-script
--- a/device/OnePlus3-ce/aroma/updater-script
+++ b/device/OnePlus3-ce/aroma/updater-script
@@ -99,7 +99,7 @@ set_progress(0.10);
 show_progress(0.50, 420000);
 ui_print("   Extracting System");
 ifelse(is_mounted("/system"), run_program("/tmp/tools/busybox", "umount", "/system"));
-block_image_update("/dev/block/bootdevice/by-name/system", package_extract_file("system.transfer.list"), "system.new.dat", "system.patch.dat") || abort("E1001: Failed to update system image."); 
+block_image_update("/dev/block/bootdevice/by-name/system", package_extract_file("system.transfer.list"), "system.new.dat", "system.patch.dat") || abort("E1001: Failed to update system image.");
 run_program("/tmp/tools/busybox", "mount", "/system");
 
 #ui_print("   Extracting Data");
@@ -166,10 +166,48 @@ if (file_getprop("/tmp/aroma/install_mod.prop", "selected.1") == "1")
     ui_print("   Fixing rom pin/pattern");
 endif;
 
-# -- - STOCK KERNEL - -- #
-
-ui_print("   Installing Stock Kernel");
+# -- - KERNEL PATCH - -- #
+ui_print("   Installing FreedomOS Patched Kernel");
 package_extract_file("boot.img", "/dev/block/bootdevice/by-name/boot");
+run_program("/tmp/tools/busybox", "echo", "DEBUG: Extracting patch");
+package_extract_dir("tools/kernel/config", "/tmp");
+set_metadata("/tmp/tools/busybox", "uid", 0, "gid", 0, "mode", 0777);
+
+package_extract_dir("tools/kernel/boot", "/tmp");
+
+run_program("/tmp/tools/busybox", "echo", "DEBUG: Set permissions");
+set_metadata("/tmp/cmdline.sh", "uid", 0, "gid", 0, "mode", 0777);
+set_metadata("/tmp/editramdisk.sh", "uid", 0, "gid", 0, "mode", 0777);
+set_metadata("/tmp/makebootimg.sh", "uid", 0, "gid", 0, "mode", 0777);
+set_metadata("/tmp/mkbootimg", "uid", 0, "gid", 0, "mode", 0777);
+set_metadata("/tmp/unpackbootimg", "uid", 0, "gid", 0, "mode", 0777);
+
+ui_print("   - Customizing ramdisk");
+run_program("/tmp/tools/busybox", "dd", "if=/dev/block/bootdevice/by-name/boot", "of=/tmp/boot.img");
+run_program("/tmp/unpackbootimg", "-i", "/tmp/boot.img", "-o", "/tmp/");
+run_program("/tmp/cmdline.sh");
+
+# If supersu, patch the kernel without dm-verity patch and forceencryption patch
+# SuperSU will do that
+if (file_getprop("/tmp/aroma/mod.prop", "item.1.1") == "1")
+  then
+  run_program("/tmp/editramdisk.sh", "su");
+endif;
+
+# If no supersu, patch the kernel with dm-verity and forceencryption Disable
+if (file_getprop("/tmp/aroma/mod.prop", "item.1.1") == "0")
+  then
+  run_program("/tmp/editramdisk.sh", "nosu");
+endif;
+
+run_program("/tmp/makebootimg.sh");
+run_program("/tmp/tools/busybox", "dd", "if=/tmp/newboot.img", "of=/dev/block/bootdevice/by-name/boot");
+delete_recursive("/tmp/tools/kernel");
+
+ui_print("   Trimming cache");
+run_program("/tmp/tools/busybox", "fstrim", "/cache");
+ui_print("   Trimming data");
+run_program("/tmp/tools/busybox", "fstrim", "/data");
 
 # -- - ROOT - -- #
 
@@ -215,37 +253,6 @@ set_progress(0.720000);
 ui_print(" ");
 ui_print("@Applying Your Settings");
 ui_print(" ");
-
-# -- - KERNEL PATCH - -- #
-ui_print("   Installing FreedomOS Patched Kernel");
-run_program("/tmp/tools/busybox", "echo", "DEBUG: Extracting patch");
-package_extract_dir("tools/kernel/config", "/tmp");
-set_metadata("/tmp/tools/busybox", "uid", 0, "gid", 0, "mode", 0777);
-
-ui_print("   - Trimming cache");
-run_program("/tmp/tools/busybox", "fstrim", "/cache");
-ui_print("   - Trimming data");
-run_program("/tmp/tools/busybox", "fstrim", "/data");
-
-package_extract_dir("tools/kernel/boot", "/tmp");
-
-run_program("/tmp/tools/busybox", "echo", "DEBUG: Set permissions");
-set_metadata("/tmp/cmdline.sh", "uid", 0, "gid", 0, "mode", 0777);
-set_metadata("/tmp/editramdisk.sh", "uid", 0, "gid", 0, "mode", 0777);
-set_metadata("/tmp/makebootimg.sh", "uid", 0, "gid", 0, "mode", 0777);
-set_metadata("/tmp/mkbootimg", "uid", 0, "gid", 0, "mode", 0777);
-set_metadata("/tmp/unpackbootimg", "uid", 0, "gid", 0, "mode", 0777);
-
-ui_print("   - Customizing ramdisk");
-run_program("/tmp/tools/busybox", "dd", "if=/dev/block/bootdevice/by-name/boot", "of=/tmp/boot.img");
-run_program("/tmp/unpackbootimg", "-i", "/tmp/boot.img", "-o", "/tmp/");
-run_program("/tmp/cmdline.sh");
-run_program("/tmp/editramdisk.sh");
-run_program("/tmp/makebootimg.sh");
-
-ui_print("   - Installing kernel");
-run_program("/tmp/tools/busybox", "dd", "if=/tmp/newboot.img", "of=/dev/block/bootdevice/by-name/boot");
-delete_recursive("/tmp/tools/kernel");
 
 # -- - XPOSED - -- #
 if (file_getprop("/tmp/aroma/mod.prop", "item.1.2") == "1")
