Update Magisk 14.3 (1437)

diff --git a/assets/tools/common/magisk/META-INF/com/google/android/updater-script b/assets/tools/common/magisk/META-INF/com/google/android/updater-script
--- a/assets/tools/common/magisk/META-INF/com/google/android/updater-script
+++ b/assets/tools/common/magisk/META-INF/com/google/android/updater-script
@@ -31,7 +31,7 @@ umask 022
 OUTFD=$2
 ZIP=$3
 
-if [ ! -d "$COMMONDIR" ]; then
+if [ ! -f $COMMONDIR/util_functions.sh ]; then
   echo "! Unable to extract zip file!"
   exit 1
 fi
@@ -49,13 +49,8 @@ ui_print "************************"
 ui_print "* Magisk v$MAGISK_VER Installer"
 ui_print "************************"
 
-ui_print "- Mounting /system, /vendor, /cache, /data"
-mount -o ro /system 2>/dev/null
-mount -o ro /vendor 2>/dev/null
-mount /cache 2>/dev/null
-mount /data 2>/dev/null
-
-[ -f /system/build.prop ] || abort "! /system could not be mounted!"
+is_mounted /data || mount /data || is_mounted /cache || mount /cache || abort "! Unable to mount partitions"
+mount_partitions
 
 # read override variables
 getvar KEEPVERITY
@@ -89,6 +84,9 @@ if $BOOTMODE; then
   rm -rf /dev/magisk/mirror/bin 2>/dev/null
 fi
 
+# Save our stock boot image dump before removing it
+mv /data/magisk/stock_boot* /data 2>/dev/null
+
 # Copy required files
 rm -rf $MAGISKBIN 2>/dev/null
 mkdir -p $MAGISKBIN
@@ -103,7 +101,7 @@ if [ -d /system/addon.d ]; then
   chmod 755 /system/addon.d/99-magisk.sh
 fi
 
-$BOOTMODE && boot_actions || recovery_actions
+$BOOTMODE || recovery_actions
 
 ##########################################################################################
 # Boot patching
@@ -119,18 +117,15 @@ cd $MAGISKBIN
 # Source the boot patcher
 . $COMMONDIR/boot_patch.sh "$BOOTIMAGE"
 
-[ -f stock_boot* ] && rm -f /data/stock_boot* 2>/dev/null
-
-ui_print "- Flashing new boot image"
-if [ -L "$BOOTIMAGE" ]; then
-  dd if=new-boot.img of="$BOOTIMAGE" bs=4096
-else
-  cat new-boot.img /dev/zero | dd of="$BOOTIMAGE" bs=4096 >/dev/null 2>&1
+if [ -f stock_boot* ]; then
+  rm -f /data/stock_boot* 2>/dev/null
+  mv stock_boot* /data
 fi
+
+flash_boot_image new-boot.img "$BOOTIMAGE"
 rm -f new-boot.img
 
 cd /
-
 # Cleanups
 $BOOTMODE || recovery_cleanup
 rm -rf $TMPDIR
