update Magisk BETA v13.0(c4377ed)

diff --git a/assets/tools/common/magisk/META-INF/com/google/android/update-binary b/assets/tools/common/magisk/META-INF/com/google/android/update-binary
--- a/assets/tools/common/magisk/META-INF/com/google/android/update-binary
+++ b/assets/tools/common/magisk/META-INF/com/google/android/update-binary
@@ -3,7 +3,7 @@
 #
 # Magisk Flash Script
 # by topjohnwu
-#
+# 
 # This script will detect, construct the environment for Magisk
 # It will then call boot_patch.sh to patch the boot image
 #
@@ -17,7 +17,6 @@ $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMO
 TMPDIR=/dev/tmp
 
 INSTALLER=$TMPDIR/magisk
-BUSYBOX=$TMPDIR/busybox
 COMMONDIR=$INSTALLER/common
 CHROMEDIR=$INSTALLER/chromeos
 COREDIR=/magisk/.core
@@ -53,134 +52,24 @@ fi
 # unzip -o "$ZIP" -d $INSTALLER
 
 ##########################################################################################
-# Functions
-##########################################################################################
-
-ui_print() {
-  if $BOOTMODE; then
-    echo "$1"
-  else
-    echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
-    echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
-  fi
-}
-
-getvar() {
-  local VARNAME=$1
-  local VALUE=$(eval echo \$"$VARNAME");
-  for FILE in /dev/.magisk /data/.magisk /cache/.magisk /system/.magisk; do
-    if [ -z "$VALUE" ]; then
-      LINE=$(cat $FILE 2>/dev/null | grep "$VARNAME=")
-      if [ ! -z "$LINE" ]; then
-        VALUE=${LINE#*=}
-      fi
-    fi
-  done
-  eval $VARNAME=\$VALUE
-}
-
-find_boot_image() {
-  if [ -z "$BOOTIMAGE" ]; then
-    for PARTITION in kern-a android_boot kernel boot lnx; do
-      BOOTIMAGE=`find /dev/block -iname "$PARTITION" | head -n 1`
-      [ ! -z $BOOTIMAGE ] && break
-    done
-  fi
-  # Recovery fallback
-  if [ -z "$BOOTIMAGE" ]; then
-    for FSTAB in /etc/*fstab*; do
-      BOOTIMAGE=`grep -E '\b/boot\b' $FSTAB | grep -oE '/dev/[a-zA-Z0-9_./-]*'`
-      [ ! -z $BOOTIMAGE ] && break
-    done
-  fi
-  [ -L "$BOOTIMAGE" ] && BOOTIMAGE=`readlink $BOOTIMAGE`
-}
-
-is_mounted() {
-  if [ ! -z "$2" ]; then
-    cat /proc/mounts | grep $1 | grep $2, >/dev/null
-  else
-    cat /proc/mounts | grep $1 >/dev/null
-  fi
-  return $?
-}
-
-mount_image() {
-  if [ ! -d "$2" ]; then
-    mount -o rw,remount rootfs /
-    mkdir -p "$2" 2>/dev/null
-    $BOOTMODE && mount -o ro,remount rootfs /
-    [ ! -d "$2" ] && return 1
-  fi
-  if ! is_mounted "$2"; then
-    LOOPDEVICE=
-    for LOOP in 0 1 2 3 4 5 6 7; do
-      if ! is_mounted "$2"; then
-        LOOPDEVICE=/dev/block/loop$LOOP
-        [ -e $LOOPDEVICE ] || mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
-        losetup $LOOPDEVICE "$1" && mount -t ext4 -o loop $LOOPDEVICE "$2"
-        if is_mounted "$2"; then
-          ui_print "- Mounting $1 to $2"
-          break;
-        fi
-      fi
-    done
-  fi
-}
-
-grep_prop() {
-  REGEX="s/^$1=//p"
-  shift
-  FILES=$@
-  if [ -z "$FILES" ]; then
-    FILES='/system/build.prop'
-  fi
-  cat $FILES 2>/dev/null | sed -n "$REGEX" | head -n 1
-}
-
-remove_system_su() {
-  if [ -f /system/bin/su -o -f /system/xbin/su ] && [ ! -f /su/bin/su ]; then
-    ui_print "! System installed root detected, mount rw :("
-    mount -o rw,remount /system
-    # SuperSU
-    if [ -e /system/bin/.ext/.su ]; then
-      mv -f /system/bin/app_process32_original /system/bin/app_process32 2>/dev/null
-      mv -f /system/bin/app_process64_original /system/bin/app_process64 2>/dev/null
-      mv -f /system/bin/install-recovery_original.sh /system/bin/install-recovery.sh 2>/dev/null
-      cd /system/bin
-      if [ -e app_process64 ]; then
-        ln -sf app_process64 app_process
-      else
-        ln -sf app_process32 app_process
-      fi
-    fi
-    rm -rf /system/.pin /system/bin/.ext /system/etc/.installed_su_daemon /system/etc/.has_su_daemon \
-    /system/xbin/daemonsu /system/xbin/su /system/xbin/sugote /system/xbin/sugote-mksh /system/xbin/supolicy \
-    /system/bin/app_process_init /system/bin/su /cache/su /system/lib/libsupol.so /system/lib64/libsupol.so \
-    /system/su.d /system/etc/install-recovery.sh /system/etc/init.d/99SuperSUDaemon /cache/install-recovery.sh \
-    /system/.supersu /cache/.supersu /data/.supersu \
-    /system/app/Superuser.apk /system/app/SuperSU /cache/Superuser.apk  2>/dev/null
-  fi
-}
-
-abort() {
-  ui_print "$1"
-  mv /sbin_tmp /sbin 2>/dev/null
-  exit 1
-}
-
-##########################################################################################
 # Detection
 ##########################################################################################
 
+if [ ! -d "$COMMONDIR" ]; then
+  echo "! Unable to extract zip file!"
+  exit 1
+fi
+
+# Load all fuctions
+. $COMMONDIR/util_functions.sh
+
 ui_print "************************"
-ui_print "* Magisk v13.0(96f8efc) Installer"
+ui_print "* Magisk v13.0(c4377ed) Installer"
 ui_print "************************"
 
-[ -d "$COMMONDIR" ] || abort "! Unable to extract zip file!"
-
-ui_print "- Mounting /system(ro), /cache, /data"
+ui_print "- Mounting /system, /vendor, /cache, /data"
 mount -o ro /system 2>/dev/null
+mount -o ro /vendor 2>/dev/null
 mount /cache 2>/dev/null
 mount /data 2>/dev/null
 
@@ -194,17 +83,8 @@ getvar BOOTIMAGE
 # Check if system root is installed and remove
 remove_system_su
 
-API=`grep_prop ro.build.version.sdk`
-ABI=`grep_prop ro.product.cpu.abi | cut -c-3`
-ABI2=`grep_prop ro.product.cpu.abi2 | cut -c-3`
-ABILONG=`grep_prop ro.product.cpu.abi`
-
-ARCH=arm
-BBPATH=armeabi-v7a
-if [ "$ABI" = "x86" ]; then ARCH=x86; BBPATH=x86; fi;
-if [ "$ABI2" = "x86" ]; then ARCH=x86; BBPATH=x86; fi;
-if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; fi;
-if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; BBPATH=x86; fi;
+# Detect version and architecture
+api_level_arch_detect
 
 [ $API -lt 21 ] && abort "! Magisk is only for Lollipop 5.0+ (SDK 21+)"
 
@@ -221,39 +101,31 @@ find_boot_image
 ##########################################################################################
 
 ui_print "- Constructing environment"
-
-if ! $BOOTMODE; then
-  # We are in custom recovery, don't trust anything in recovery, use those in /system
-  # Extract busybox from Magisk Manager, it's pure static binary so there will be no issues
-  unzip -o $COMMONDIR/magisk.apk lib/$BBPATH/libbusybox.so -d $BUSYBOX
-  mv $BUSYBOX/lib/*/libbusybox.so $BUSYBOX/busybox
-  rm -rf $BUSYBOX/lib
-  chmod +x $BUSYBOX/busybox
-  $BUSYBOX/busybox --install -s $BUSYBOX
-  # Prefer bin in /system, fallback to bundled busybox if a tool doesn't exist
-  export PATH=/system/bin:/system/xbin:$BUSYBOX
-  # Clear out possible lib paths, let the binary find them itself
-  export LD_LIBRARY_PATH=
-  # Temporarily block out all custom recovery binaries/libs
-  mv /sbin /sbin_tmp
-fi
-
+  
 is_mounted /data && MAGISKBIN=/data/magisk || MAGISKBIN=/cache/data_bin
 
 # Copy required files
 rm -rf $MAGISKBIN 2>/dev/null
 mkdir -p $MAGISKBIN
 cp -af $BINDIR/. $COMMONDIR/. $MAGISKBIN
-
 chmod -R 755 $MAGISKBIN
-chcon -hR u:object_r:system_file:s0 $MAGISKBIN
+
+# addon.d
+if [ -d /system/addon.d ]; then
+  ui_print "- Adding addon.d survival script"
+  mount -o rw,remount /system
+  cp $INSTALLER/addon.d/99-magisk.sh /system/addon.d/99-magisk.sh
+  chmod 755 /system/addon.d/99-magisk.sh
+fi
 
 ##########################################################################################
 # Magisk Image
 ##########################################################################################
 
+$BOOTMODE || recovery_actions
+
 # Fix SuperSU.....
-$BOOTMODE && $BINDIR/magiskpolicy --live "allow fsck * * *"
+$BOOTMODE && $BINDIR/magisk magiskpolicy --live "allow fsck * * *"
 
 if (is_mounted /data); then
   IMG=/data/magisk.img
@@ -269,9 +141,11 @@ else
   $BINDIR/magisk --createimg $IMG 64M
 fi
 
-mount_image $IMG /magisk
+if ! is_mounted /magisk; then
+  ui_print "- Mounting $IMG to /magisk"
+  MAGISKLOOP=`$BINDIR/magisk --mountimg $IMG /magisk`
+fi
 is_mounted /magisk || abort "! Magisk image mount failed..."
-MAGISKLOOP=$LOOPDEVICE
 
 # Core folders
 mkdir -p $COREDIR/props $COREDIR/post-fs-data.d $COREDIR/service.d 2>/dev/null
@@ -315,28 +189,22 @@ if [ -f chromeos ]; then
   mv new-boot.img.signed new-boot.img
 fi
 
-if is_mounted /data; then
-  rm -f /data/stock_boot* 2>/dev/null
-  mv stock_boot* /data 2>/dev/null
-fi
+[ -f stock_boot* ] && rm -f /data/stock_boot* 2>/dev/null
 
 ui_print "- Flashing new boot image"
 if [ -L "$BOOTIMAGE" ]; then
   dd if=new-boot.img of="$BOOTIMAGE" bs=4096
 else
-  cat new-boot.img /dev/zero | dd of="$BOOTIMAGE" bs=4096
+  cat new-boot.img /dev/zero | dd of="$BOOTIMAGE" bs=4096 >/dev/null 2>&1
 fi
 rm -f new-boot.img
 
 cd /
 
 if ! $BOOTMODE; then
-  mv /sbin_tmp /sbin
-  ui_print "- Unmounting partitions"
-  umount /magisk
-  losetup -d $MAGISKLOOP 2>/dev/null
+  $BINDIR/magisk --umountimg /magisk $MAGISKLOOP
   rmdir /magisk
-  umount -l /system
+  recovery_cleanup
 fi
 
 ui_print "- Done"
