Update magisk v13 beta 0980cb6

diff --git a/assets/tools/common/magisk/META-INF/com/google/android/update-binary b/assets/tools/common/magisk/META-INF/com/google/android/update-binary
--- a/assets/tools/common/magisk/META-INF/com/google/android/update-binary
+++ b/assets/tools/common/magisk/META-INF/com/google/android/update-binary
@@ -1,26 +1,26 @@
 #!/sbin/sh
 ##########################################################################################
 #
-# Magisk Boot Image Patcher
+# Magisk Flash Script
 # by topjohnwu
-# 
-# This zip will patch your boot image with Magisk support
+#
+# This script will detect, construct the environment for Magisk
+# It will then call boot_patch.sh to patch the boot image
 #
 ##########################################################################################
 
-MAGISK=true
-
 # Detect whether in boot mode
 ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
+$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
 
 # This path should work in any cases
 TMPDIR=/dev/tmp
 
 INSTALLER=$TMPDIR/magisk
+BUSYBOX=$TMPDIR/busybox
 COMMONDIR=$INSTALLER/common
-BOOTTMP=$TMPDIR/boottmp
-COREDIR=/magisk/.core
 CHROMEDIR=$INSTALLER/chromeos
+COREDIR=/magisk/.core
 
 # Default permissions
 umask 022
@@ -48,9 +48,9 @@ if [ "$?" -eq "0" ]; then
   done
 fi
 
-mkdir -p $INSTALLER
-cd $INSTALLER
-unzip -o "$ZIP"
+# rm -rf $TMPDIR 2>/dev/null
+# mkdir -p $INSTALLER $BUSYBOX
+# unzip -o "$ZIP" -d $INSTALLER
 
 ##########################################################################################
 # Functions
@@ -59,7 +59,7 @@ unzip -o "$ZIP"
 ui_print() {
   if $BOOTMODE; then
     echo "$1"
-  else 
+  else
     echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
     echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
   fi
@@ -81,16 +81,19 @@ getvar() {
 
 find_boot_image() {
   if [ -z "$BOOTIMAGE" ]; then
-    for PARTITION in kern-a KERN-A android_boot ANDROID_BOOT kernel KERNEL boot BOOT lnx LNX; do
-      BOOTIMAGE=`readlink /dev/block/by-name/$PARTITION || readlink /dev/block/platform/*/by-name/$PARTITION || readlink /dev/block/platform/*/*/by-name/$PARTITION`
-      if [ ! -z "$BOOTIMAGE" ]; then break; fi
+    for PARTITION in kern-a android_boot kernel boot lnx; do
+      BOOTIMAGE=`find /dev/block -iname "$PARTITION" | head -n 1`
+      [ ! -z $BOOTIMAGE ] && break
     done
   fi
+  # Recovery fallback
   if [ -z "$BOOTIMAGE" ]; then
-    FSTAB="/etc/recovery.fstab"
-    [ ! -f "$FSTAB" ] && FSTAB="/etc/recovery.fstab.bak"
-    [ -f "$FSTAB" ] && BOOTIMAGE=`grep -E '\b/boot\b' "$FSTAB" | grep -oE '/dev/[a-zA-Z0-9_./-]*'`
+    for FSTAB in /etc/*fstab*; do
+      BOOTIMAGE=`grep -E '\b/boot\b' $FSTAB | grep -oE '/dev/[a-zA-Z0-9_./-]*'`
+      [ ! -z $BOOTIMAGE ] && break
+    done
   fi
+  [ -L "$BOOTIMAGE" ] && BOOTIMAGE=`readlink $BOOTIMAGE`
 }
 
 is_mounted() {
@@ -105,29 +108,18 @@ is_mounted() {
 mount_image() {
   if [ ! -d "$2" ]; then
     mount -o rw,remount rootfs /
-    mkdir -p $2 2>/dev/null
-    ($BOOTMODE) && mount -o ro,remount rootfs /
+    mkdir -p "$2" 2>/dev/null
+    $BOOTMODE && mount -o ro,remount rootfs /
     [ ! -d "$2" ] && return 1
   fi
-  if (! is_mounted $2); then
+  if ! is_mounted "$2"; then
     LOOPDEVICE=
     for LOOP in 0 1 2 3 4 5 6 7; do
-      if (! is_mounted $2); then
+      if ! is_mounted "$2"; then
         LOOPDEVICE=/dev/block/loop$LOOP
-        if [ ! -f "$LOOPDEVICE" ]; then
-          mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
-        fi
-        losetup $LOOPDEVICE $1
-        if [ "$?" -eq "0" ]; then
-          mount -t ext4 -o loop $LOOPDEVICE $2
-          if (! is_mounted $2); then
-            /system/bin/toolbox mount -t ext4 -o loop $LOOPDEVICE $2
-          fi
-          if (! is_mounted $2); then
-            /system/bin/toybox mount -t ext4 -o loop $LOOPDEVICE $2
-          fi
-        fi
-        if (is_mounted $2); then
+        [ -e $LOOPDEVICE ] || mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
+        losetup $LOOPDEVICE "$1" && mount -t ext4 -o loop $LOOPDEVICE "$2"
+        if is_mounted "$2"; then
           ui_print "- Mounting $1 to $2"
           break;
         fi
@@ -171,51 +163,33 @@ remove_system_su() {
   fi
 }
 
-# --cpio-add <incpio> <mode> <entry> <infile>
-cpio_add() {
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-add ramdisk.cpio $1 $2 $3
-}
-
-# --cpio-extract <incpio> <entry> <outfile>
-cpio_extract() {
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-extract ramdisk.cpio $1 $2
-}
-
-# --cpio-mkdir <incpio> <mode> <entry>
-cpio_mkdir() {
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-mkdir ramdisk.cpio $1 $2
+abort() {
+  ui_print "$1"
+  mv /sbin_tmp /sbin 2>/dev/null
+  exit 1
 }
 
 ##########################################################################################
 # Detection
 ##########################################################################################
 
-ui_print "*****************************"
-ui_print "Magisk v12.0 Boot Image Patcher"
-ui_print "*****************************"
+ui_print "************************"
+ui_print "* Magisk v13.0(96f8efc) Installer"
+ui_print "************************"
 
-if [ ! -d "$COMMONDIR" ]; then
-  ui_print "! Failed: Unable to extract zip file!"
-  exit 1
-fi
+[ -d "$COMMONDIR" ] || abort "! Unable to extract zip file!"
 
 ui_print "- Mounting /system(ro), /cache, /data"
 mount -o ro /system 2>/dev/null
 mount /cache 2>/dev/null
 mount /data 2>/dev/null
 
-if [ ! -f '/system/build.prop' ]; then
-  ui_print "! Failed: /system could not be mounted!"
-  exit 1
-fi
+[ -f /system/build.prop ] || abort "! /system could not be mounted!"
 
 # read override variables
 getvar KEEPVERITY
 getvar KEEPFORCEENCRYPT
 getvar BOOTIMAGE
-
-[ -z $KEEPVERITY ] && KEEPVERITY=false
-[ -z $KEEPFORCEENCRYPT ] && KEEPFORCEENCRYPT=false
 
 # Check if system root is installed and remove
 remove_system_su
@@ -226,31 +200,21 @@ ABI2=`grep_prop ro.product.cpu.abi2 | cut -c-3`
 ABILONG=`grep_prop ro.product.cpu.abi`
 
 ARCH=arm
-IS64BIT=false
-if [ "$ABI" = "x86" ]; then ARCH=x86; fi;
-if [ "$ABI2" = "x86" ]; then ARCH=x86; fi;
-if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; IS64BIT=true; fi;
-if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; IS64BIT=true; fi;
+BBPATH=armeabi-v7a
+if [ "$ABI" = "x86" ]; then ARCH=x86; BBPATH=x86; fi;
+if [ "$ABI2" = "x86" ]; then ARCH=x86; BBPATH=x86; fi;
+if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; fi;
+if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; BBPATH=x86; fi;
 
-
-if [ "$API" -lt "21" ]; then
-  ui_print "! Magisk is only for Lollipop 5.0+ (SDK 21+)"
-  exit 1
-fi
+[ $API -lt 21 ] && abort "! Magisk is only for Lollipop 5.0+ (SDK 21+)"
 
 ui_print "- Device platform: $ARCH"
 
 BINDIR=$INSTALLER/$ARCH
 chmod -R 755 $CHROMEDIR $BINDIR
 
-SYSTEMLIB=/system/lib
-$IS64BIT && SYSTEMLIB=/system/lib64
-
 find_boot_image
-if [ -z $BOOTIMAGE ]; then
-  ui_print "! Unable to detect boot image"
-  exit 1
-fi
+[ -z $BOOTIMAGE ] && abort "! Unable to detect boot image"
 
 ##########################################################################################
 # Environment
@@ -258,25 +222,31 @@ fi
 
 ui_print "- Constructing environment"
 
+if ! $BOOTMODE; then
+  # We are in custom recovery, don't trust anything in recovery, use those in /system
+  # Extract busybox from Magisk Manager, it's pure static binary so there will be no issues
+  unzip -o $COMMONDIR/magisk.apk lib/$BBPATH/libbusybox.so -d $BUSYBOX
+  mv $BUSYBOX/lib/*/libbusybox.so $BUSYBOX/busybox
+  rm -rf $BUSYBOX/lib
+  chmod +x $BUSYBOX/busybox
+  $BUSYBOX/busybox --install -s $BUSYBOX
+  # Prefer bin in /system, fallback to bundled busybox if a tool doesn't exist
+  export PATH=/system/bin:/system/xbin:$BUSYBOX
+  # Clear out possible lib paths, let the binary find them itself
+  export LD_LIBRARY_PATH=
+  # Temporarily block out all custom recovery binaries/libs
+  mv /sbin /sbin_tmp
+fi
+
 is_mounted /data && MAGISKBIN=/data/magisk || MAGISKBIN=/cache/data_bin
 
 # Copy required files
 rm -rf $MAGISKBIN 2>/dev/null
 mkdir -p $MAGISKBIN
-cp -af $BINDIR/busybox $BINDIR/magiskboot $BINDIR/magiskpolicy $COMMONDIR/magisk.apk \
-       $COMMONDIR/init.magisk.rc  $COMMONDIR/custom_ramdisk_patch.sh $COMMONDIR/magic_mask.sh $MAGISKBIN
-# Legacy support
-ln -sf /data/magisk/magiskpolicy $MAGISKBIN/sepolicy-inject
+cp -af $BINDIR/. $COMMONDIR/. $MAGISKBIN
 
 chmod -R 755 $MAGISKBIN
-chcon -h u:object_r:system_file:s0 $MAGISKBIN $MAGISKBIN/*
-
-# Temporary busybox for installation
-rm -rf $TMPDIR/busybox 2>/dev/null
-mkdir -p $TMPDIR/busybox
-$BINDIR/busybox --install -s $TMPDIR/busybox
-rm -f $TMPDIR/busybox/su $TMPDIR/busybox/sh $TMPDIR/busybox/reboot
-PATH=$TMPDIR/busybox:$PATH
+chcon -hR u:object_r:system_file:s0 $MAGISKBIN
 
 ##########################################################################################
 # Magisk Image
@@ -296,25 +266,22 @@ if [ -f $IMG ]; then
   ui_print "- $IMG detected!"
 else
   ui_print "- Creating $IMG"
-  make_ext4fs -l 64M -a /magisk -S $COMMONDIR/file_contexts_image $IMG
+  $BINDIR/magisk --createimg $IMG 64M
 fi
 
 mount_image $IMG /magisk
-if (! is_mounted /magisk); then
-  ui_print "! Magisk image mount failed..."
-  exit 1
-fi
+is_mounted /magisk || abort "! Magisk image mount failed..."
 MAGISKLOOP=$LOOPDEVICE
 
-# Core folders and scripts
-mkdir -p $COREDIR/bin $COREDIR/props $COREDIR/magiskhide $COREDIR/post-fs-data.d $COREDIR/service.d 2>/dev/null
-cp -af $COMMONDIR/magiskhide/. $COREDIR/magiskhide
-cp -af $BINDIR/resetprop $BINDIR/magiskhide $BINDIR/su $BINDIR/magiskpolicy $COREDIR/bin
-# Legacy support
-ln -sf $COREDIR/bin/resetprop $MAGISKBIN/resetprop
+# Core folders
+mkdir -p $COREDIR/props $COREDIR/post-fs-data.d $COREDIR/service.d 2>/dev/null
 
-chmod -R 755 $COREDIR/bin $COREDIR/magiskhide $COREDIR/post-fs-data.d $COREDIR/service.d
-chown -R 0.0 $COREDIR/bin $COREDIR/magiskhide $COREDIR/post-fs-data.d $COREDIR/service.d
+chmod 755 $COREDIR/post-fs-data.d $COREDIR/service.d
+chown 0.0 $COREDIR/post-fs-data.d $COREDIR/service.d
+
+# Legacy cleanup
+mv $COREDIR/magiskhide/hidelist $COREDIR/hidelist 2>/dev/null
+rm -rf $COREDIR/magiskhide $COREDIR/bin
 
 ##########################################################################################
 # Unpack boot
@@ -322,205 +289,54 @@ chown -R 0.0 $COREDIR/bin $COREDIR/magiskhide $COREDIR/post-fs-data.d $COREDIR/s
 
 ui_print "- Found Boot Image: $BOOTIMAGE"
 
-rm -rf $BOOTTMP 2>/dev/null
-mkdir -p $BOOTTMP
-cd $BOOTTMP
-
-ui_print "- Unpacking boot image"
-LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --unpack $BOOTIMAGE
-if [ $? -ne 0 ]; then
-  ui_print "! Unable to unpack boot image"
-  exit 1
-fi
-
-##########################################################################################
-# Ramdisk restores
-##########################################################################################
-
 # Update our previous backup to new format if exists
 if [ -f /data/stock_boot.img ]; then
-  SHA1=`LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --sha1 /data/stock_boot.img | tail -n 1`
+  SHA1=`$BINDIR/magiskboot --sha1 /data/stock_boot.img | tail -n 1`
   STOCKDUMP=/data/stock_boot_${SHA1}.img
   mv /data/stock_boot.img $STOCKDUMP
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --compress $STOCKDUMP
+  $BINDIR/magiskboot --compress $STOCKDUMP
 fi
 
-# Test patch status and do restore, after this section, ramdisk.cpio.orig is guaranteed to exist
-SUPERSU=false
-ui_print "- Checking patch status"
-LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-test ramdisk.cpio
-case $? in
-  0 )  # Stock boot
-    ui_print "- Backing up stock boot image"
-    rm -f /data/stock_boot*
-    SHA1=`LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --sha1 $BOOTIMAGE | tail -n 1`
-    is_mounted /data && STOCKDUMP=/data/stock_boot_${SHA1}.img || STOCKDUMP=/cache/stock_boot_${SHA1}.img
-    dd if=$BOOTIMAGE of=$STOCKDUMP
-    LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --compress $STOCKDUMP
-    cp -af ramdisk.cpio ramdisk.cpio.orig
-    ;;
-  1 )  # Magisk patched
-    # Find SHA1 of stock boot image
-    if [ -z $SHA1 ]; then
-      LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-extract ramdisk.cpio init.magisk.rc init.magisk.rc
-      SHA1=`grep_prop "# STOCKSHA1" init.magisk.rc`
-      [ ! -z $SHA1 ] && STOCKDUMP=/data/stock_boot_${SHA1}.img
-      rm -f init.magisk.rc
-    fi
-    ui_print "- Restoring ramdisk backup"
-    LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-restore ramdisk.cpio
-    if [ $? -ne 0 ]; then
-      # Restore failed, try to find original 
-      ui_print "! Cannot restore from ramdisk backup"
-      ui_print "- Finding stock boot image backup"
-      if [ -f ${STOCKDUMP}.gz ]; then
-        LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --decompress ${STOCKDUMP}.gz stock_boot.img
-        LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --unpack stock_boot.img
-        rm -f stock_boot.img
-      else
-        ui_print "! Cannot find stock boot image backup"
-        ui_print "! Will still try to complete installation"
-      fi
-    fi
-    cp -af ramdisk.cpio ramdisk.cpio.orig
-    ;;
-  2 ) # SuperSU patched
-    SUPERSU=true
-    ui_print "- SuperSU patched boot detected!"
-    ui_print "- Adding ramdisk patch script for SuperSU"
-    cp -af $COMMONDIR/custom_ramdisk_patch.sh /data/custom_ramdisk_patch.sh
-    ui_print "- We are using SuperSU's own tools, mounting su.img"
-    is_mounted /data && SUIMG=/data/su.img || SUIMG=/cache/su.img
-    mount_image $SUIMG /su
-    SUPERSULOOP=$LOOPDEVICE
-    if (is_mounted /su); then
-      ui_print "- Restoring ramdisk backup with sukernel"
-      LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-restore ramdisk.cpio ramdisk.cpio.orig
-      if [ $? -ne 0 ]; then
-        ui_print "! Cannot restore from ramdisk"
-        ui_print "- Finding stock boot image backup with sukernel"
-        LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --restore ramdisk.cpio stock_boot.img
-        if [ $? -eq 0 ]; then
-          LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --unpack stock_boot.img
-          cp -af ramdisk.cpio ramdisk.cpio.orig
-          rm stock_boot.img
-        else
-          ui_print "! Cannot find stock boot image backup"
-          exit 1
-        fi
-      fi
-    else
-      ui_print "! SuperSU image mount failed..."
-      ui_print "! Magisk scripts are placed correctly"
-      ui_print "! Flash SuperSU immediately to finish installation"
-      exit 1
-    fi
-    ;;
-esac
+SOURCEDMODE=true
+cd $MAGISKBIN
 
-##########################################################################################
-# Boot image patches
-##########################################################################################
-
-# All ramdisk patch commands are stored in a separate script
-ui_print "- Patching ramdisk"
-
-if $SUPERSU; then
-  # Use sukernel to patch ramdisk, so we can use its own tools to backup
-  sh $COMMONDIR/custom_ramdisk_patch.sh $BOOTTMP/ramdisk.cpio
-
-  # Create ramdisk backups
-  LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-backup ramdisk.cpio.orig ramdisk.cpio ramdisk.cpio
-
-else
-  # The common patches
-  $KEEPVERITY || LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-patch-dmverity ramdisk.cpio
-  $KEEPFORCEENCRYPT || LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-patch-forceencrypt ramdisk.cpio
-
-  # Add magisk entrypoint
-  cpio_extract init.rc init.rc
-  grep "import /init.magisk.rc" init.rc >/dev/null || sed -i '1,/.*import.*/s/.*import.*/import \/init.magisk.rc\n&/' init.rc
-  sed -i "/selinux.reload_policy/d" init.rc
-  cpio_add 750 init.rc init.rc
-
-  # sepolicy patches
-  cpio_extract sepolicy sepolicy
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskpolicy --load sepolicy --save sepolicy --minimal
-  cpio_add 644 sepolicy sepolicy
-
-  # Add new items
-  cpio_mkdir 755 magisk
-
-  [ ! -z $SHA1 ] && echo "# STOCKSHA1=$SHA1" >> $COMMONDIR/init.magisk.rc
-  cpio_add 750 init.magisk.rc $COMMONDIR/init.magisk.rc
-
-  cpio_add 750 sbin/magic_mask.sh $COMMONDIR/magic_mask.sh
-
-  # Create ramdisk backups
-  LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-backup ramdisk.cpio ramdisk.cpio.orig
-fi
-
-rm -f ramdisk.cpio.orig
-
-##########################################################################################
-# Repack and flash
-##########################################################################################
-
-# Hexpatches
-
-# Remove Samsung RKP in stock kernel
-LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --hexpatch kernel \
-49010054011440B93FA00F71E9000054010840B93FA00F7189000054001840B91FA00F7188010054 \
-A1020054011440B93FA00F7140020054010840B93FA00F71E0010054001840B91FA00F7181010054
-
-ui_print "- Repacking boot image"
-LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --repack $BOOTIMAGE
-
-case $? in
-  1 )
-    ui_print "! Unable to repack boot image!"
-    exit 1
-    ;;
-  2 )
-    ui_print "! Boot partition space insufficient"
-    ui_print "! Remove ramdisk backups and try again"
-    LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --cpio-rm ramdisk.cpio -r .backup
-    LD_LIBRARY_PATH=$SYSTEMLIB $BINDIR/magiskboot --repack $BOOTIMAGE
-    if [ $? -eq 2 ]; then
-      ui_print "! Boot partition size still too small..."
-      ui_print "! Unable to install Magisk"
-      exit 1
-    fi
-    ;;
-esac
+# Source the boot patcher
+. $COMMONDIR/boot_patch.sh "$BOOTIMAGE"
 
 # Sign chromeos boot
 if [ -f chromeos ]; then
-  cp -af $CHROMEDIR/. $MAGISKBIN/chromeos
-  echo > config
-  echo > bootloader
-  LD_LIBRARY_PATH=$SYSTEMLIB $CHROMEDIR/futility vbutil_kernel --pack new-boot.img.signed --keyblock $CHROMEDIR/kernel.keyblock --signprivate $CHROMEDIR/kernel_data_key.vbprivk --version 1 --vmlinuz new-boot.img --config config --arch arm --bootloader bootloader --flags 0x1
-  rm -f new-boot.img
+  echo > empty
+
+  $CHROMEDIR/futility vbutil_kernel --pack new-boot.img.signed \
+  --keyblock $CHROMEDIR/kernel.keyblock --signprivate $CHROMEDIR/kernel_data_key.vbprivk \
+  --version 1 --vmlinuz new-boot.img --config empty --arch arm --bootloader empty --flags 0x1
+
+  rm -f empty new-boot.img
   mv new-boot.img.signed new-boot.img
 fi
 
+if is_mounted /data; then
+  rm -f /data/stock_boot* 2>/dev/null
+  mv stock_boot* /data 2>/dev/null
+fi
+
 ui_print "- Flashing new boot image"
-[ ! -L $BOOTIMAGE ] && dd if=/dev/zero of=$BOOTIMAGE bs=4096 2>/dev/null
-dd if=new-boot.img of=$BOOTIMAGE bs=4096
+if [ -L "$BOOTIMAGE" ]; then
+  dd if=new-boot.img of="$BOOTIMAGE" bs=4096
+else
+  cat new-boot.img /dev/zero | dd of="$BOOTIMAGE" bs=4096
+fi
+rm -f new-boot.img
 
 cd /
 
 if ! $BOOTMODE; then
+  mv /sbin_tmp /sbin
   ui_print "- Unmounting partitions"
   umount /magisk
-  losetup -d $MAGISKLOOP
+  losetup -d $MAGISKLOOP 2>/dev/null
   rmdir /magisk
-  if $SUPERSU; then
-    umount /su
-    losetup -d $SUPERSULOOP
-    rmdir /su
-  fi
-  umount /system
+  umount -l /system
 fi
 
 ui_print "- Done"
