update supersu 2.78 for op2

diff --git a/assets/tools/oneplus2/supersu/META-INF/com/google/android/update-binary b/assets/tools/oneplus2/supersu/META-INF/com/google/android/update-binary
--- a/assets/tools/oneplus2/supersu/META-INF/com/google/android/update-binary
+++ b/assets/tools/oneplus2/supersu/META-INF/com/google/android/update-binary
@@ -34,10 +34,12 @@
 # Overridable variables (shell):
 #   BIN - Location of architecture specific files (native folder)
 #   COM - Location of common files (APK folder)
+#   LESSLOGGING - Reduce ui_print logging (true/false)
 #   NOOVERRIDE - Do not read variables from /system/.supersu or
 #                /data/.supersu
 #
-# Overridable variables (shell, /system/.supersu, /data/.supersu):
+# Overridable variables (shell, /system/.supersu, /cache/.supersu,
+# /data/.supersu):
 #   SYSTEMLESS - Do a system-less install? (true/false, 6.0+ only)
 #   PATCHBOOTIMAGE - Automatically patch boot image? (true/false,
 #                    SYSTEMLESS only)
@@ -45,7 +47,13 @@
 #   STOCKBOOTIMAGE - Stock boot image location (PATCHBOOTIMAGE only)
 #   BINDSYSTEMXBIN - Poor man's overlay on /system/xbin (true/false,
 #                    SYSTEMLESS only)
-# Shell overrides all, /data/.supersu overrides /system/.supersu
+#   PERMISSIVE - Set sepolicy to fake-permissive (true/false, PATCHBOOTIMAGE
+#                only)
+#   KEEPVERITY - Do not remove dm-verity (true/false, PATCHBOOTIMAGE only)
+#   KEEPFORCEENCRYPT - Do not replace forceencrypt with encryptable (true/
+#                      false, PATCHBOOTIMAGE only)
+# Shell overrides all, /data/.supersu overrides /cache/.supersu overrides
+# /system/.supersu
 #
 # Note that if SELinux is set to enforcing, the daemonsu binary expects
 # to be run at startup (usually from install-recovery.sh, 99SuperSUDaemon,
@@ -157,7 +165,7 @@
 # *1: su.pie for 17+ x86(_32) only
 #
 # 22+   ARCH/supolicy                 /su/bin/supolicy_wrapped            0755    u:object_r:system_file:s0   required
-# 22+   /su/bin/su (symlink) *2       /su/lib/supolicy                    0755    u:object_r:system_file:s0   required
+# 22+   /su/bin/su (symlink) *2       /su/bin/supolicy                    0755    u:object_r:system_file:s0   required
 # 22+   ARCH/libsupol.so              /su/lib/libsupol.so                 0644    u:object_r:system_file:s0   required
 # *2: when called this way, su sets the correct LD_LIBRARY_PATH and calls supolicy_wrapped
 #
@@ -175,20 +183,24 @@
 #
 # - Uses the supolicy tool to patch the sepolicy file
 # - Injects /sbin/launch_daemon.sh
+# - Creates /su
 # - Removes /verity_key
 # - Patches /*fstab*
 # --- Removes support_scfs and verify flags
-# --- Changes forceencrypt into encryptable
+# --- Changes forceencrypt/forcefdeorfbe into encryptable
+# --- Set ro mounts to use noatime
 # - Patches /init.rc
-# --- Adds mkdir /su
-# --- Adds a sukernel.mount property trigger that mounts /data/su.img to /su
-# --- Adds the daemonsu service that launches /sbin/launch_daemon.sh
+# --- Removes 'setprop selinux.reload_policy' occurences
 # --- Adds a SuperSU:PATCH marker with the version of the sukernel tool
 # --- Adds a SuperSU:STOCK marker listed the SHA1 of the original boot image
+# - Adds /init.supersu.rc
+# --- Adds a sukernel.mount property trigger that mounts /data/su.img to /su
+# --- Adds the daemonsu service that launches /sbin/launch_daemon.sh
+# --- Adds exec /sbin/launch_daemonsu.sh on post-fs-data
 # - Patches /init.environ.rc
 # --- Adds PATH variable if it does not exist
 # --- Prepends /su/bin to the PATH variable
-# - Patches /file_contexts
+# - Patches /file_contexts[.bin]
 # --- Adds a default context for file existing in the /su mount
 #
 # In case this documentation becomes outdated, please note that the sukernel
@@ -203,6 +215,10 @@
 # The boot image patcher currently only supports GZIP compressed ramdisks, and
 # boot images in the standard Android boot image format.
 #
+# During boot image patch, /data/custom_ramdisk_patch.sh will be called,
+# with the name of the ramdisk cpio file as parameter. The script must
+# replace the input file and return a 0 exit code.
+#
 # Just before flashing, the boot image patcher will call
 # /data/custom_boot_image_patch.sh with the name of the patched boot image
 # as parameter. A device-specific patcher can further patch the boot image
@@ -214,7 +230,7 @@ ZIP=$3
 getvar() {
   local VARNAME=$1
   local VALUE=$(eval echo \$"$VARNAME");
-  for FILE in /data/.supersu /system/.supersu; do
+  for FILE in /data/.supersu /cache/.supersu /system/.supersu; do
     if [ -z "$VALUE" ]; then
       LINE=$(cat $FILE 2>/dev/null | grep "$VARNAME=")
       if [ ! -z "$LINE" ]; then
@@ -225,31 +241,48 @@ getvar() {
   eval $VARNAME=\$VALUE
 }
 
-if [ -z "$NOOVERRIDE" ]; then
-  # read override variables
-  getvar SYSTEMLESS
-  getvar PATCHBOOTIMAGE
-  getvar BOOTIMAGE
-  getvar STOCKBOOTIMAGE
-  getvar BINDSYSTEMXBIN
+readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
+if [ "$?" -eq "0" ]; then
+  # rerouted to log file, we don't want our ui_print commands going there
+  OUTFD=0
+
+  # we are probably running in embedded mode, see if we can find the right fd
+  # we know the fd is a pipe and that the parent updater may have been started as
+  # 'update-binary 3 fd zipfile'
+  for FD in `ls /proc/$$/fd`; do
+    readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
+    if [ "$?" -eq "0" ]; then
+      ps | grep " 3 $FD " | grep -v grep >/dev/null
+      if [ "$?" -eq "0" ]; then
+        OUTFD=$FD
+        break
+      fi
+    fi
+  done
 fi
 
-if [ -z "$SYSTEMLESS" ]; then
-  # detect if we need systemless, based on Android version and boot image
-  SYSTEMLESS=true
+ui_print_always() {
+  echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
+  echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
+}
+
+if [ -z "$LESSLOGGING" ]; then
+  LESSLOGGING=false
 fi
-if [ -z "$PATCHBOOTIMAGE" ]; then
-  # only if we end up doing a system-less install
-  PATCHBOOTIMAGE=true
-fi
-if [ -z "$BINDSYSTEMXBIN" ]; then
-  # causes launch_daemonsu to bind over /system/xbin
-  BINDSYSTEMXBIN=true
-fi
+
+UI_PRINT_LAST=""
 
 ui_print() {
-  echo -n -e "ui_print $1\n" > /proc/self/fd/$OUTFD
-  echo -n -e "ui_print\n" > /proc/self/fd/$OUTFD
+  if (! $LESSLOGGING); then
+    UI_PRINT_LAST="$1"
+    ui_print_always "$1"
+  fi
+}
+
+ui_print_less() {
+  if ($LESSLOGGING); then
+    ui_print_always "$1"
+  fi
 }
 
 ch_con() {
@@ -428,9 +461,9 @@ wipe_system_files_if_present() {
       /system/etc/install-recovery_original.sh
       /system/bin/install-recovery_original.sh
       /system/bin/app_process32_original
-      /system/bin/app_process32_exposed
+      /system/bin/app_process32_xposed
       /system/bin/app_process64_original
-      /system/bin/app_process64_exposed
+      /system/bin/app_process64_xposed
       /system/bin/app_process_init
     "
     for FILE in $SPECIALSYSTEMFILES; do
@@ -542,7 +575,14 @@ check_zero() {
     if [ $? -eq 0 ]; then
       if [ ! -z "$2" ]; then ui_print "$2"; fi
     else
-      if [ ! -z "$3" ]; then ui_print "$3"; fi
+      if [ ! -z "$3" ]; then
+        if [ ! -z "$1" ]; then
+          ui_print_less "$1"
+        else
+          ui_print_less "$UI_PRINT_LAST"
+        fi
+        ui_print_always "$3";
+      fi
       CONTINUE=false
     fi
   fi
@@ -664,7 +704,7 @@ detect_systemless_required() {
   LD_LIBRARY_PATH=$RAMDISKLIB $BIN/supolicy --file /sutmp/sepolicy /data/security/current/sepolicy
   set_perm 1000 1000 0644 /data/security/current/sepolicy u:object_r:security_file:s0
 
-  for i in seapp_contexts file_contexts property_contexts service_contexts selinux_version; do
+  for i in seapp_contexts file_contexts file_contexts.bin property_contexts service_contexts selinux_version; do
     ln -s /$i /data/security/current/$i
   done
 
@@ -678,9 +718,9 @@ detect_systemless_required() {
 }
 
 ui_print " "
-ui_print "*****************"
-ui_print "SuperSU installer"
-ui_print "*****************"
+ui_print        "*****************"
+ui_print_always "SuperSU installer"
+ui_print        "*****************"
 
 ui_print "- Mounting /system, /data and rootfs"
 
@@ -697,6 +737,42 @@ if [ -z "$BIN" ]; then
     ui_print "- BAD RECOVERY DETECTED, NO UNZIP, ABORTING"
     exit 1
   fi
+fi
+
+if [ -z "$NOOVERRIDE" ]; then
+  # read override variables
+  getvar SYSTEMLESS
+  getvar PATCHBOOTIMAGE
+  getvar BOOTIMAGE
+  getvar STOCKBOOTIMAGE
+  getvar BINDSYSTEMXBIN
+  getvar PERMISSIVE
+  getvar KEEPVERITY
+  getvar KEEPFORCEENCRYPT
+fi
+if [ -z "$SYSTEMLESS" ]; then
+  # detect if we need systemless, based on Android version and boot image
+  SYSTEMLESS=true
+fi
+if [ -z "$PATCHBOOTIMAGE" ]; then
+  # only if we end up doing a system-less install
+  PATCHBOOTIMAGE=true
+fi
+if [ -z "$BINDSYSTEMXBIN" ]; then
+  # causes launch_daemonsu to bind over /system/xbin, disabled by default
+  BINDSYSTEMXBIN=false
+fi
+if [ -z "$PERMISSIVE" ]; then
+  # don't make everything fake-permissive
+  PERMISSIVE=false
+fi
+if [ -z "$KEEPVERITY" ]; then
+  # we don't keep dm-verity by default
+  KEEPVERITY=false
+fi
+if [ -z "$KEEPFORCEENCRYPT" ]; then
+  # we don't keep forceencrypt by default
+  KEEPFORCEENCRYPT=false
 fi
 
 API=$(cat /system/build.prop | grep "ro.build.version.sdk=" | dd bs=1 skip=21 count=2)
@@ -783,7 +859,7 @@ if [ -z "$BIN" ]; then
 fi
 
 # execute binaries from ramdisk
-chmod 0755 $BIN/*
+chmod -R 0755 $BIN/*
 RAMDISKLIB=$BIN:$SYSTEMLIB
 
 if [ "$API" -ge "19" ]; then
@@ -1009,15 +1085,16 @@ else
 
   ui_print "- Creating image"
 
-  SUIMGSIZE=32M
-  if [ ! -f "$SUIMG" ]; then
-    make_ext4fs -l $SUIMGSIZE -a /su -S $COM/file_contexts_image $SUIMG
-  fi
-  if [ ! -f "$SUIMG" ]; then
-    LD_LIBRARY_PATH=$SYSTEMLIB /system/bin/make_ext4fs -l $SUIMGSIZE -a /su -S $COM/file_contexts_image $SUIMG
-  fi
+  # we want a 96M image, for SuperSU files and potential mods such as systemless xposed
+  # attempt smaller sizes on failure, and hope the launch_daemonsu.sh script succeeds
+  # in resizing to 96M later
+  for SUIMGSIZE in 96M 64M 32M 16M; do
+    if [ ! -f "$SUIMG" ]; then make_ext4fs -l $SUIMGSIZE -a /su -S $COM/file_contexts_image $SUIMG; fi
+    if [ ! -f "$SUIMG" ]; then LD_LIBRARY_PATH=$SYSTEMLIB /system/bin/make_ext4fs -l $SUIMGSIZE -a /su -S $COM/file_contexts_image $SUIMG; fi
+  done
+
   if [ -f "$SUIMG" ]; then
-    LD_LIBRARY_PATH=$SYSTEMLIB /system/bin/e2fsck -p $SUIMG
+    LD_LIBRARY_PATH=$SYSTEMLIB /system/bin/e2fsck -p -f $SUIMG
   fi
 
   ui_print "- Mounting image"
@@ -1029,12 +1106,18 @@ else
   for LOOP in 0 1 2 3 4 5 6 7; do
     if (! is_mounted /su); then
       LOOPDEVICE=/dev/block/loop$LOOP
-      mknod $LOOPDEVICE b 7 $LOOP
+      if [ ! -f "$LOOPDEVICE" ]; then
+        mknod $LOOPDEVICE b 7 $LOOP
+      fi
       losetup $LOOPDEVICE $SUIMG
-      mount -t ext4 -o loop $LOOPDEVICE /su
-      /system/bin/toolbox mount -t ext4 -o loop $LOOPDEVICE /su
-      if (! is_mounted /su); then
-        /system/bin/toybox mount -t ext4 -o loop $LOOPDEVICE /su
+      if [ "$?" -eq "0" ]; then
+        mount -t ext4 -o loop $LOOPDEVICE /su
+        if (! is_mounted /su); then
+          /system/bin/toolbox mount -t ext4 -o loop $LOOPDEVICE /su
+        fi
+        if (! is_mounted /su); then
+          /system/bin/toybox mount -t ext4 -o loop $LOOPDEVICE /su
+        fi
       fi
       if (is_mounted /su); then
         break;
@@ -1045,7 +1128,7 @@ else
   ui_print "- Creating paths"
 
   mkdir /su/bin
-  set_perm 0 0 0755 /su/bin
+  set_perm 0 0 0751 /su/bin
   mkdir /su/xbin
   set_perm 0 0 0755 /su/xbin
   mkdir /su/lib
@@ -1107,16 +1190,17 @@ else
 
   if ($PATCHBOOTIMAGE); then
     ui_print " "
-    ui_print "******************"
-    ui_print "Boot image patcher"
-    ui_print "******************"
+    ui_print        "******************"
+    ui_print_always "Boot image patcher"
+    ui_print        "******************"
 
     ui_print "- Finding boot image"
     find_boot_image
 
     CONTINUE=true
     if [ -z "$BOOTIMAGE" ]; then
-      ui_print "--- Boot image: not found, aborting"
+      ui_print_less "$UI_PRINT_LAST"
+      ui_print_always "--- Boot image: not found, aborting"
       CONTINUE=false
     else
       ui_print "--- Boot image: $BOOTIMAGE"
@@ -1128,6 +1212,12 @@ else
 
     rm -rf /sutmp
     mkdir /sutmp
+
+    IMAGETYPE=android
+    LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --bootimg-type $BOOTIMAGE
+    if [ $? -eq 2 ]; then
+      IMAGETYPE=chromeos
+    fi
 
     check_zero_def "- Extracting ramdisk" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --bootimg-extract-ramdisk $BOOTIMAGE /sutmp/ramdisk.packed"
     check_zero_def "- Decompressing ramdisk" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --ungzip /sutmp/ramdisk.packed /sutmp/ramdisk"
@@ -1141,17 +1231,28 @@ else
         if ($CONTINUE); then
           LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --restore /sutmp/ramdisk /sutmp/stock_boot.img
           if [ $? -ne 0 ]; then
-            ui_print "--- Restore failed, aborting"
+            ui_print_always "--- Stock restore failed, attempting ramdisk restore"
             CONTINUE=false
           else
-            ui_print "--- Backup restored"
+            ui_print "--- Stock backup restored"
             STOCKBOOTIMAGE=/sutmp/stock_boot.img
           fi
         fi
 
         check_zero_def "- Extracting ramdisk" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --bootimg-extract-ramdisk /sutmp/stock_boot.img /sutmp/ramdisk.packed"
         check_zero_def "- Decompressing ramdisk" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --ungzip /sutmp/ramdisk.packed /sutmp/ramdisk"
-        check_zero "- Checking patch status" "" "--- Already patched, aborting" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --patch-test /sutmp/ramdisk"
+        check_zero "- Checking patch status" "" "--- Already patched, attempting ramdisk restore" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --patch-test /sutmp/ramdisk"
+
+        if (! $CONTINUE); then
+          LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-restore /sutmp/ramdisk /sutmp/ramdisk
+          if [ $? -ne 0 ]; then
+            ui_print_always "--- Ramdisk restore failed, aborting"
+          else
+            ui_print "--- Ramdisk backup restored (OTA impossible)"
+            CONTINUE=true
+          fi
+          check_zero "- Checking patch status" "" "--- Already patched, aborting" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --patch-test /sutmp/ramdisk"
+        fi
       else
         ui_print "- Creating backup"
         rm /data/stock_boot_*.img
@@ -1166,37 +1267,76 @@ else
     fi
 
     if ($CONTINUE); then
+      cp_perm 0 0 0644 /sutmp/ramdisk /sutmp/ramdisk.original
+
       ui_print "- Patching sepolicy"
 
       check_zero_def "" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-extract /sutmp/ramdisk sepolicy /sutmp/sepolicy"
 
       if ($CONTINUE); then
-        LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/supolicy --file /sutmp/sepolicy /sutmp/sepolicy_patched
-        if [ ! -f "/sutmp/sepolicy_patched" ]; then
-          ui_print "--- Failure, aborting"
+        if ($PERMISSIVE); then
+          LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/supolicy --file /sutmp/sepolicy /sutmp/sepolicy.patched "permissive *"
+        else
+          LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/supolicy --file /sutmp/sepolicy /sutmp/sepolicy.patched
+        fi
+        if [ ! -f "/sutmp/sepolicy.patched" ]; then
+          ui_print_less "$UI_PRINT_LAST"
+          ui_print_always "--- Failure, aborting"
           CONTINUE=false
         fi
       fi
 
-      check_zero_def "" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-add /sutmp/ramdisk /sutmp/ramdisk 644 sepolicy /sutmp/sepolicy_patched"
+      check_zero_def "" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-add /sutmp/ramdisk /sutmp/ramdisk 644 sepolicy /sutmp/sepolicy.patched"
     fi
 
-    check_zero_def "- Patching daemon launcher" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-add /sutmp/ramdisk /sutmp/ramdisk 700 sbin/launch_daemonsu.sh $COM/launch_daemonsu.sh"
+    check_zero_def "- Adding daemon launcher" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-add /sutmp/ramdisk /sutmp/ramdisk 700 sbin/launch_daemonsu.sh $COM/launch_daemonsu.sh"
+    check_zero_def "- Adding init script" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-add /sutmp/ramdisk /sutmp/ramdisk 750 init.supersu.rc $COM/init.supersu.rc"
 
-    check_zero_def "- Patching init.*.rc, fstabs, file_contexts, dm-verity" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --patch /sutmp/ramdisk /sutmp/ramdisk $STOCKBOOTIMAGE"
+    check_zero_def "- Creating mount point" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-mkdir /sutmp/ramdisk /sutmp/ramdisk 755 su"
+
+    COMMAND="LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --patch /sutmp/ramdisk /sutmp/ramdisk $STOCKBOOTIMAGE"
+    if ($KEEPVERITY); then
+      COMMAND="$COMMAND --keep-verity"
+    fi
+    if ($KEEPFORCEENCRYPT); then
+      COMMAND="$COMMAND --keep-forceencrypt"
+    fi
+    check_zero_def "- Patching init.*.rc, fstabs, file_contexts, dm-verity" "$COMMAND"
+
+    if [ -f "/data/custom_ramdisk_patch.sh" ]; then
+        check_zero_def "- Calling user ramdisk patch script" "sh /data/custom_ramdisk_patch.sh /sutmp/ramdisk"
+    fi
+
+    check_zero_def "- Creating ramdisk backup" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --cpio-backup /sutmp/ramdisk.original /sutmp/ramdisk /sutmp/ramdisk"
 
     check_zero_def "- Compressing ramdisk" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --gzip /sutmp/ramdisk /sutmp/ramdisk.packed"
+
+    if [ "$IMAGETYPE" = "chromeos" ]; then
+      $BIN/chromeos/futility vbutil_kernel --get-vmlinuz $STOCKBOOTIMAGE --vmlinuz-out /sutmp/boot.chromeos.img
+      STOCKBOOTIMAGE=/sutmp/boot.chromeos.img
+    fi
+
     check_zero_def "- Creating boot image" "LD_LIBRARY_PATH=$SYSTEMLIB /su/bin/sukernel --bootimg-replace-ramdisk $STOCKBOOTIMAGE /sutmp/ramdisk.packed /sutmp/boot.img"
 
-    if ($CONTINUE); then
-      if [ -f "/data/custom_boot_image_patch.sh" ]; then
-        ui_print "- Calling user script"
-        USER=$(sh /data/custom_boot_image_patch.sh /sutmp/boot.img)
-        if [ $? -ne 0 ]; then
-          ui_print "--- Failure, aborting"
-          CONTINUE=false
-        fi
+    if [ "$IMAGETYPE" = "chromeos" ]; then
+      ui_print "- Signing boot image"
+      $BIN/chromeos/futility vbutil_kernel --pack /sutmp/boot.img.signed --keyblock $COM/chromeos/kernel.keyblock --signprivate $COM/chromeos/kernel_data_key.vbprivk --version 1 --vmlinuz /sutmp/boot.img --config $COM/chromeos/kernel.config --arch arm --bootloader $COM/chromeos/kernel.bootloader --flags 0x1
+      if [ -f "/sutmp/boot.img.signed" ]; then
+        rm -rf /sutmp/boot.img
+        mv /sutmp/boot.img.signed /sutmp/boot.img
+      else
+        ui_print_less "$UI_PRINT_LAST"
+        ui_print_always "--- Failure, aborting"
+        $CONTINUE=false
       fi
+    fi
+
+    # might return 1 even if we do not want to abort
+    ui_print "- Applying hex patches"
+    /su/bin/sukernel --hexpatch $COM/hexpatch /sutmp/boot.img /sutmp/boot.img
+
+    if [ -f "/data/custom_boot_image_patch.sh" ]; then
+        check_zero_def "- Calling user boot image patch script" "sh /data/custom_boot_image_patch.sh /sutmp/boot.img"
     fi
 
     if ($CONTINUE); then
@@ -1229,20 +1369,28 @@ else
   ui_print "*************************"
   ui_print "    IMPORTANT NOTICES    "
   ui_print "*************************"
-  ui_print "If TWRP offers to install"
-  ui_print "SuperSU, do *NOT* let it!"
-  ui_print "*************************"
+
+  TWRP2=$(cat /tmp/recovery.log | grep "ro.twrp.version=2");
+  if [ $? -eq 0 ]; then
+    ui_print "If TWRP offers to install"
+    ui_print "SuperSU, do *NOT* let it!"
+    ui_print "*************************"
+  fi
+
   ui_print "First reboot may take a  "
   ui_print "few minutes. It can also "
   ui_print "loop a few times. Do not "
   ui_print "interrupt the process!   "
   ui_print "*************************"
   ui_print " "
-  sleep 5
+
+  if (! $LESSLOGGING); then
+    sleep 5
+  fi
 fi
 
 ui_print "- Unmounting /system"
 umount /system
 
-ui_print "- Done !"
+ui_print_always "- Done !"
 exit 0
